version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      - poc_camunda_DB__uri=postgresql://postgres:postgres@db:5432/poc_camunda
      - poc_camunda_DB__connect_args={}
    volumes:
      - .:/home/app/web
    depends_on:
      - db
  db:
    build: postgres
    image: poc_camunda_postgres-13-alpine-multi-user
    volumes:
      - $HOME/.postgres/poc_camunda_db/data/postgresql:/var/lib/postgresql/data
    ports:
      - 5435:5432
    environment:
      - POSTGRES_DBS=poc_camunda, poc_camunda_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
